<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MoojPay.Domain\MoojPay.Domain.csproj" />
    <ProjectReference Include="..\MoojPay.Modules.Marketplace\MoojPay.Modules.Marketplace.csproj" />
    <ProjectReference Include="..\MoojPay.Modules.Identity\MoojPay.Modules.Identity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
